import { fal } from "@fal-ai/client";
import { z } from "zod";
import type { AspectRatio } from "@gmc/shared";

// Thin image-generation interface so the backend stays a one-file swap
// (build plan §6). The only implementation today is fal.ai Nano Banana Pro:
// text-to-image for reference-free prompts, the edit endpoint when reference
// images (identity / style / product) attach.
//
// Endpoint + schema verified live via `pnpm fal:test` — run it after any
// fal-side change before trusting a pipeline run (the standard rule: never
// integrate against guessed schemas).

export type ImageGenRequest = {
  prompt: string;
  aspectRatio: AspectRatio;
  /** Reference images (signed URLs). Presence routes to the edit endpoint. */
  referenceImageUrls?: string[];
  /** For logs, e.g. "concept 3 / hook 1 / 4:5". */
  label: string;
};

export type ImageGenResult = {
  /** Provider-hosted URL of the generated image (short-lived — download it). */
  imageUrl: string;
  costUsd: number;
  raw: unknown;
};

export interface ImageProvider {
  readonly name: string;
  /** creatives.model value for rows generated by this provider. */
  readonly model: "nano_banana";
  /** Known ahead of the call — the run cost cap checks before generating. */
  costPerImageUsd(req?: ImageGenRequest): number;
  generate(req: ImageGenRequest): Promise<ImageGenResult>;
}

export const FAL_TEXT_TO_IMAGE_ENDPOINT = "fal-ai/nano-banana-pro";
export const FAL_EDIT_ENDPOINT = "fal-ai/nano-banana-pro/edit";
// 1K/2K renders bill $0.15/image (4K doubles it — we never request 4K).
const FAL_COST_PER_IMAGE_USD = 0.15;
// The edit endpoint takes multiple reference images; more than a handful
// dilutes the composition, so the compiler's picks are capped here too.
const MAX_REFERENCE_IMAGES = 6;

const RETRYABLE_NETWORK_RE =
  /fetch failed|ECONNRESET|ECONNREFUSED|ETIMEDOUT|socket hang up|UND_ERR|other side closed|429|502|503/i;
const RETRY_BACKOFF_MS = 3000;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// What we rely on from the response — loose on purpose (extra fields pass).
// fal:test validates this against the live endpoint and prints the raw shape.
export const FalImageResultSchema = z.object({
  images: z
    .array(z.object({ url: z.string().url() }).passthrough())
    .min(1),
});

export function getFalApiKey(): string | null {
  return process.env.FAL_API_KEY ?? null;
}

export function createFalNanoBananaProvider(apiKey: string): ImageProvider {
  fal.config({ credentials: apiKey });

  async function callFal(req: ImageGenRequest): Promise<unknown> {
    const refs = (req.referenceImageUrls ?? []).slice(0, MAX_REFERENCE_IMAGES);
    const endpoint = refs.length > 0 ? FAL_EDIT_ENDPOINT : FAL_TEXT_TO_IMAGE_ENDPOINT;
    const result = await fal.subscribe(endpoint, {
      input: {
        prompt: req.prompt,
        aspect_ratio: req.aspectRatio,
        resolution: "2K",
        num_images: 1,
        output_format: "png",
        ...(refs.length > 0 ? { image_urls: refs } : {}),
      },
      logs: false,
    });
    return result.data;
  }

  return {
    name: "fal.ai Nano Banana Pro",
    model: "nano_banana",
    costPerImageUsd: () => FAL_COST_PER_IMAGE_USD,
    async generate(req) {
      let data: unknown;
      try {
        data = await callFal(req);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        if (!RETRYABLE_NETWORK_RE.test(message)) throw err;
        console.warn(
          `[image-provider] ${req.label}: transient failure, retrying once: ${message.slice(0, 200)}`,
        );
        await sleep(RETRY_BACKOFF_MS);
        data = await callFal(req);
      }

      const parsed = FalImageResultSchema.safeParse(data);
      if (!parsed.success) {
        throw new Error(
          `[image-provider] ${req.label}: unexpected response shape (re-run pnpm fal:test): ${JSON.stringify(data).slice(0, 300)}`,
        );
      }
      return {
        imageUrl: parsed.data.images[0]!.url,
        costUsd: FAL_COST_PER_IMAGE_USD,
        raw: data,
      };
    },
  };
}
